import type { Database } from '@rp-vibe-ideation/inthub-entities';
import {
  ProviderCategory,
  OrgStatus,
  ProviderAccountStatus,
  CredentialStatus,
  ConfigPurpose,
  ConfigStatus,
  RuntimeType,
  RuntimeStatus,
  IntegrationTypeStatus,
  IntegrationStatus,
  ProvisioningStatus,
  TargetEntityType,
  Severity,
  RunStatus,
  TaskType,
  TaskStatus,
} from '@rp-vibe-ideation/inthub-entities';

export const database: Database = {
  // ── Providers (shared catalog) ───────────────────────────────────────────
  providers: [
    {
      id: 'aws',
      name: 'AWS',
      category: ProviderCategory.Cloud,
      description: 'Amazon Web Services cloud platform',
    },
    {
      id: 'gcp',
      name: 'GCP',
      category: ProviderCategory.Cloud,
      description: 'Google Cloud Platform',
    },
    {
      id: 'azure',
      name: 'Azure',
      category: ProviderCategory.Cloud,
      description: 'Microsoft Azure cloud platform',
    },
    {
      id: 'qualys',
      name: 'Qualys',
      category: ProviderCategory.Vulnerability,
      description: 'Cloud-based vulnerability management',
    },
    {
      id: 'tenable',
      name: 'Tenable',
      category: ProviderCategory.Vulnerability,
      description: 'Vulnerability assessment and management',
    },
    {
      id: 'datadog',
      name: 'DataDog',
      category: ProviderCategory.SIEM,
      description: 'Monitoring and security analytics',
    },
    {
      id: 'qradar',
      name: 'QRadar',
      category: ProviderCategory.SIEM,
      description: 'IBM SIEM platform',
    },
    {
      id: 'splunk',
      name: 'Splunk',
      category: ProviderCategory.SIEM,
      description: 'Data platform for security',
    },
    {
      id: 'snowflake',
      name: 'Snowflake',
      category: ProviderCategory.Data,
      description: 'Cloud data warehouse',
    },
  ],

  // ── Orgs ─────────────────────────────────────────────────────────────────
  orgs: [
    {
      id: 'org-acme',
      name: 'Acme Corp',
      status: OrgStatus.Active,
      createdAt: '2022-03-01T00:00:00Z',
    },
    {
      id: 'org-titan',
      name: 'Titan Security',
      status: OrgStatus.Active,
      createdAt: '2023-01-15T00:00:00Z',
    },
    {
      id: 'org-vertex',
      name: 'Vertex Labs',
      status: OrgStatus.Active,
      createdAt: '2024-06-01T00:00:00Z',
    },
  ],

  // ── Provider Accounts ────────────────────────────────────────────────────
  providerAccounts: [
    // Acme Corp
    {
      id: 'pa-acme-aws',
      orgId: 'org-acme',
      providerId: 'aws',
      name: 'Acme AWS Production',
      externalId: '123456789012',
      status: ProviderAccountStatus.Active,
      region: 'us-east-1',
    },
    {
      id: 'pa-acme-qualys',
      orgId: 'org-acme',
      providerId: 'qualys',
      name: 'Acme Qualys',
      externalId: 'acme-qualys-tenant',
      status: ProviderAccountStatus.Active,
    },
    {
      id: 'pa-acme-datadog',
      orgId: 'org-acme',
      providerId: 'datadog',
      name: 'Acme DataDog',
      externalId: 'acme-dd-org',
      status: ProviderAccountStatus.Active,
    },
    {
      id: 'pa-acme-snowflake',
      orgId: 'org-acme',
      providerId: 'snowflake',
      name: 'Acme Snowflake',
      externalId: 'acme.snowflakecomputing.com',
      status: ProviderAccountStatus.Active,
    },
    {
      id: 'pa-acme-splunk',
      orgId: 'org-acme',
      providerId: 'splunk',
      name: 'Acme Splunk',
      externalId: 'acme-splunk-cloud',
      status: ProviderAccountStatus.Active,
    },
    // Titan Security
    {
      id: 'pa-titan-aws',
      orgId: 'org-titan',
      providerId: 'aws',
      name: 'Titan AWS',
      externalId: '987654321098',
      status: ProviderAccountStatus.Active,
      region: 'eu-west-1',
    },
    {
      id: 'pa-titan-tenable',
      orgId: 'org-titan',
      providerId: 'tenable',
      name: 'Titan Tenable.io',
      externalId: 'titan-tenable-io',
      status: ProviderAccountStatus.Active,
    },
    {
      id: 'pa-titan-snowflake',
      orgId: 'org-titan',
      providerId: 'snowflake',
      name: 'Titan Snowflake',
      externalId: 'titan.snowflakecomputing.com',
      status: ProviderAccountStatus.Active,
    },
    {
      id: 'pa-titan-qradar',
      orgId: 'org-titan',
      providerId: 'qradar',
      name: 'Titan QRadar',
      externalId: 'titan-qradar-on-cloud',
      status: ProviderAccountStatus.Inactive,
    },
    // Vertex Labs
    {
      id: 'pa-vertex-aws',
      orgId: 'org-vertex',
      providerId: 'aws',
      name: 'Vertex AWS Dev',
      externalId: '111222333444',
      status: ProviderAccountStatus.Active,
      region: 'us-west-2',
    },
    {
      id: 'pa-vertex-qualys',
      orgId: 'org-vertex',
      providerId: 'qualys',
      name: 'Vertex Qualys',
      externalId: 'vertex-qualys-trial',
      status: ProviderAccountStatus.Active,
    },
    {
      id: 'pa-vertex-snowflake',
      orgId: 'org-vertex',
      providerId: 'snowflake',
      name: 'Vertex Snowflake',
      externalId: 'vertex.snowflakecomputing.com',
      status: ProviderAccountStatus.Active,
    },
  ],

  // ── Credential Types ─────────────────────────────────────────────────────
  credentialTypes: [
    {
      id: 'ct-aws-iam-role',
      providerId: 'aws',
      name: 'IAM Role',
      description: 'AWS IAM Role assumed via STS',
      fields: ['roleArn', 'externalId'],
    },
    {
      id: 'ct-aws-access-key',
      providerId: 'aws',
      name: 'Access Key',
      description: 'AWS access key and secret',
      fields: ['accessKeyId', 'secretAccessKey'],
    },
    {
      id: 'ct-qualys-api-key',
      providerId: 'qualys',
      name: 'API Key',
      description: 'Qualys API username and password',
      fields: ['username', 'password'],
    },
    {
      id: 'ct-tenable-api-key',
      providerId: 'tenable',
      name: 'API Key',
      description: 'Tenable.io access and secret keys',
      fields: ['accessKey', 'secretKey'],
    },
    {
      id: 'ct-datadog-api-key',
      providerId: 'datadog',
      name: 'API Key',
      description: 'DataDog API and application keys',
      fields: ['apiKey', 'appKey'],
    },
    {
      id: 'ct-snowflake-keypair',
      providerId: 'snowflake',
      name: 'Key Pair',
      description: 'Snowflake RSA key pair authentication',
      fields: ['user', 'privateKeyPath', 'privateKeyPassphrase'],
    },
    {
      id: 'ct-splunk-token',
      providerId: 'splunk',
      name: 'HEC Token',
      description: 'Splunk HTTP Event Collector token',
      fields: ['hecToken', 'endpoint'],
    },
    {
      id: 'ct-qradar-token',
      providerId: 'qradar',
      name: 'SEC Token',
      description: 'QRadar SEC authentication token',
      fields: ['secToken', 'host'],
    },
  ],

  // ── Credentials ──────────────────────────────────────────────────────────
  credentials: [
    // Acme
    {
      id: 'cred-acme-aws-role',
      providerAccountId: 'pa-acme-aws',
      credentialTypeId: 'ct-aws-iam-role',
      name: 'Acme AWS IAM Role',
      vaultPath: 'secret/acme/aws/iam-role',
      status: CredentialStatus.Active,
      expiresAt: '2026-12-01T00:00:00Z',
      rotatedAt: '2025-12-01T00:00:00Z',
    },
    {
      id: 'cred-acme-qualys',
      providerAccountId: 'pa-acme-qualys',
      credentialTypeId: 'ct-qualys-api-key',
      name: 'Acme Qualys API',
      vaultPath: 'secret/acme/qualys/api',
      status: CredentialStatus.Expiring,
      expiresAt: '2026-04-20T00:00:00Z',
      rotatedAt: '2025-04-20T00:00:00Z',
    },
    {
      id: 'cred-acme-datadog',
      providerAccountId: 'pa-acme-datadog',
      credentialTypeId: 'ct-datadog-api-key',
      name: 'Acme DataDog API',
      vaultPath: 'secret/acme/datadog/api',
      status: CredentialStatus.Active,
      rotatedAt: '2025-10-01T00:00:00Z',
    },
    {
      id: 'cred-acme-snowflake',
      providerAccountId: 'pa-acme-snowflake',
      credentialTypeId: 'ct-snowflake-keypair',
      name: 'Acme Snowflake Key Pair',
      vaultPath: 'secret/acme/snowflake/keypair',
      status: CredentialStatus.Active,
      rotatedAt: '2025-09-15T00:00:00Z',
    },
    {
      id: 'cred-acme-splunk',
      providerAccountId: 'pa-acme-splunk',
      credentialTypeId: 'ct-splunk-token',
      name: 'Acme Splunk HEC Token',
      vaultPath: 'secret/acme/splunk/hec',
      status: CredentialStatus.Expired,
      expiresAt: '2025-12-01T00:00:00Z',
    },
    // Titan
    {
      id: 'cred-titan-aws-role',
      providerAccountId: 'pa-titan-aws',
      credentialTypeId: 'ct-aws-iam-role',
      name: 'Titan AWS IAM Role',
      vaultPath: 'secret/titan/aws/iam-role',
      status: CredentialStatus.Active,
      expiresAt: '2027-06-01T00:00:00Z',
      rotatedAt: '2025-06-01T00:00:00Z',
    },
    {
      id: 'cred-titan-tenable',
      providerAccountId: 'pa-titan-tenable',
      credentialTypeId: 'ct-tenable-api-key',
      name: 'Titan Tenable API',
      vaultPath: 'secret/titan/tenable/api',
      status: CredentialStatus.Active,
      rotatedAt: '2025-11-01T00:00:00Z',
    },
    {
      id: 'cred-titan-snowflake',
      providerAccountId: 'pa-titan-snowflake',
      credentialTypeId: 'ct-snowflake-keypair',
      name: 'Titan Snowflake Key Pair',
      vaultPath: 'secret/titan/snowflake/keypair',
      status: CredentialStatus.Active,
      rotatedAt: '2025-08-01T00:00:00Z',
    },
    // Vertex
    {
      id: 'cred-vertex-aws-key',
      providerAccountId: 'pa-vertex-aws',
      credentialTypeId: 'ct-aws-access-key',
      name: 'Vertex AWS Access Key',
      vaultPath: 'secret/vertex/aws/access-key',
      status: CredentialStatus.Active,
      rotatedAt: '2025-07-01T00:00:00Z',
    },
    {
      id: 'cred-vertex-qualys',
      providerAccountId: 'pa-vertex-qualys',
      credentialTypeId: 'ct-qualys-api-key',
      name: 'Vertex Qualys API',
      vaultPath: 'secret/vertex/qualys/api',
      status: CredentialStatus.Active,
      rotatedAt: '2025-10-15T00:00:00Z',
    },
  ],

  // ── Config Schemas ───────────────────────────────────────────────────────
  configSchemas: [
    {
      id: 'cs-qualys-integration',
      providerId: 'qualys',
      purpose: ConfigPurpose.Integration,
      name: 'Qualys Integration Config',
      schema: {
        type: 'object',
        properties: {
          domain: { type: 'string', description: 'Qualys platform domain' },
          pageSize: { type: 'number', default: 1000 },
        },
        required: ['domain'],
      },
    },
    {
      id: 'cs-datadog-integration',
      providerId: 'datadog',
      purpose: ConfigPurpose.Integration,
      name: 'DataDog Integration Config',
      schema: {
        type: 'object',
        properties: {
          site: { type: 'string', description: 'DataDog site (e.g. datadoghq.com)' },
          lookbackDays: { type: 'number', default: 7 },
        },
        required: ['site'],
      },
    },
    {
      id: 'cs-tenable-integration',
      providerId: 'tenable',
      purpose: ConfigPurpose.Integration,
      name: 'Tenable Integration Config',
      schema: {
        type: 'object',
        properties: {
          chunkSize: { type: 'number', default: 500 },
        },
      },
    },
    {
      id: 'cs-snowflake-integration',
      providerId: 'snowflake',
      purpose: ConfigPurpose.Integration,
      name: 'Snowflake Target Config',
      schema: {
        type: 'object',
        properties: {
          warehouse: { type: 'string' },
          database: { type: 'string' },
          schema: { type: 'string' },
        },
        required: ['warehouse', 'database', 'schema'],
      },
    },
  ],

  // ── Configs ──────────────────────────────────────────────────────────────
  configs: [
    // Acme
    {
      id: 'cfg-acme-qualys',
      providerAccountId: 'pa-acme-qualys',
      configSchemaId: 'cs-qualys-integration',
      values: { domain: 'qualysguard.acme.com', pageSize: 2000 },
      status: ConfigStatus.Active,
    },
    {
      id: 'cfg-acme-datadog',
      providerAccountId: 'pa-acme-datadog',
      configSchemaId: 'cs-datadog-integration',
      values: { site: 'datadoghq.com', lookbackDays: 14 },
      status: ConfigStatus.Active,
    },
    {
      id: 'cfg-acme-snowflake',
      providerAccountId: 'pa-acme-snowflake',
      configSchemaId: 'cs-snowflake-integration',
      values: { warehouse: 'INTEGRATION_WH', database: 'SECURITY_DB', schema: 'RAW' },
      status: ConfigStatus.Active,
    },
    // Titan
    {
      id: 'cfg-titan-tenable',
      providerAccountId: 'pa-titan-tenable',
      configSchemaId: 'cs-tenable-integration',
      values: { chunkSize: 1000 },
      status: ConfigStatus.Active,
    },
    {
      id: 'cfg-titan-snowflake',
      providerAccountId: 'pa-titan-snowflake',
      configSchemaId: 'cs-snowflake-integration',
      values: { warehouse: 'TITAN_WH', database: 'SECURITY', schema: 'INGEST' },
      status: ConfigStatus.Active,
    },
    // Vertex
    {
      id: 'cfg-vertex-qualys',
      providerAccountId: 'pa-vertex-qualys',
      configSchemaId: 'cs-qualys-integration',
      values: { domain: 'qualysguard.vertexlabs.io' },
      status: ConfigStatus.Draft,
    },
  ],

  // ── Integration Runtimes ─────────────────────────────────────────────────
  integrationRuntimes: [
    {
      id: 'rt-astronomer-prod',
      name: 'Astronomer Production',
      type: RuntimeType.Astronomer,
      status: RuntimeStatus.Active,
      url: 'https://astronomer.acme-mssp.io',
    },
    {
      id: 'rt-n8n-prod',
      name: 'N8N Production',
      type: RuntimeType.N8N,
      status: RuntimeStatus.Active,
      url: 'https://n8n.acme-mssp.io',
    },
    {
      id: 'rt-eks-prod',
      name: 'EKS Production Cluster',
      type: RuntimeType.EKS,
      status: RuntimeStatus.Active,
    },
  ],

  // ── Integration Types ────────────────────────────────────────────────────
  integrationTypes: [
    {
      id: 'it-qualys-snowflake-v1',
      name: 'Qualys → Snowflake',
      sourceProviderId: 'qualys',
      targetProviderId: 'snowflake',
      runtimeId: 'rt-astronomer-prod',
      version: '1.0.0',
      dagId: 'qualys_to_snowflake_v1',
      status: IntegrationTypeStatus.Active,
      description: 'Pulls vulnerability findings from Qualys and loads into Snowflake',
    },
    {
      id: 'it-qualys-snowflake-v2',
      name: 'Qualys → Snowflake',
      sourceProviderId: 'qualys',
      targetProviderId: 'snowflake',
      runtimeId: 'rt-astronomer-prod',
      version: '2.0.0',
      dagId: 'qualys_to_snowflake_v2',
      status: IntegrationTypeStatus.Active,
      description: 'V2: incremental load with deduplication',
    },
    {
      id: 'it-datadog-snowflake-v1',
      name: 'DataDog → Snowflake',
      sourceProviderId: 'datadog',
      targetProviderId: 'snowflake',
      runtimeId: 'rt-astronomer-prod',
      version: '1.0.0',
      dagId: 'datadog_to_snowflake_v1',
      status: IntegrationTypeStatus.Active,
      description: 'Exports DataDog security signals to Snowflake',
    },
    {
      id: 'it-tenable-snowflake-v1',
      name: 'Tenable → Snowflake',
      sourceProviderId: 'tenable',
      targetProviderId: 'snowflake',
      runtimeId: 'rt-astronomer-prod',
      version: '1.0.0',
      dagId: 'tenable_to_snowflake_v1',
      status: IntegrationTypeStatus.Active,
      description: 'Pulls Tenable scan results into Snowflake',
    },
    {
      id: 'it-qualys-splunk-v1',
      name: 'Qualys → Splunk',
      sourceProviderId: 'qualys',
      targetProviderId: 'splunk',
      runtimeId: 'rt-n8n-prod',
      version: '1.0.0',
      status: IntegrationTypeStatus.Deprecated,
      description: 'Legacy: Qualys findings forwarded to Splunk via N8N',
    },
  ],

  // ── Integrations ─────────────────────────────────────────────────────────
  integrations: [
    // Acme Corp
    {
      id: 'int-acme-qualys-snow-1',
      orgId: 'org-acme',
      integrationTypeId: 'it-qualys-snowflake-v2',
      sourceAccountId: 'pa-acme-qualys',
      targetAccountId: 'pa-acme-snowflake',
      sourceCredentialId: 'cred-acme-qualys',
      targetCredentialId: 'cred-acme-snowflake',
      name: 'Acme Qualys → Snowflake',
      status: IntegrationStatus.Active,
      createdAt: '2022-06-01T00:00:00Z',
      lastRunAt: '2026-04-06T02:00:00Z',
    },
    {
      id: 'int-acme-dd-snow-1',
      orgId: 'org-acme',
      integrationTypeId: 'it-datadog-snowflake-v1',
      sourceAccountId: 'pa-acme-datadog',
      targetAccountId: 'pa-acme-snowflake',
      sourceCredentialId: 'cred-acme-datadog',
      targetCredentialId: 'cred-acme-snowflake',
      name: 'Acme DataDog → Snowflake',
      status: IntegrationStatus.Active,
      createdAt: '2022-09-01T00:00:00Z',
      lastRunAt: '2026-04-06T03:00:00Z',
    },
    {
      id: 'int-acme-qualys-splunk-1',
      orgId: 'org-acme',
      integrationTypeId: 'it-qualys-splunk-v1',
      sourceAccountId: 'pa-acme-qualys',
      targetAccountId: 'pa-acme-splunk',
      sourceCredentialId: 'cred-acme-qualys',
      targetCredentialId: 'cred-acme-splunk',
      name: 'Acme Qualys → Splunk (legacy)',
      status: IntegrationStatus.Failed,
      createdAt: '2022-03-15T00:00:00Z',
      lastRunAt: '2025-11-30T04:00:00Z',
    },
    // Titan Security
    {
      id: 'int-titan-tenable-snow-1',
      orgId: 'org-titan',
      integrationTypeId: 'it-tenable-snowflake-v1',
      sourceAccountId: 'pa-titan-tenable',
      targetAccountId: 'pa-titan-snowflake',
      sourceCredentialId: 'cred-titan-tenable',
      targetCredentialId: 'cred-titan-snowflake',
      name: 'Titan Tenable → Snowflake',
      status: IntegrationStatus.Active,
      createdAt: '2023-04-01T00:00:00Z',
      lastRunAt: '2026-04-06T01:00:00Z',
    },
    {
      id: 'int-titan-qualys-snow-1',
      orgId: 'org-titan',
      integrationTypeId: 'it-qualys-snowflake-v1',
      sourceAccountId: 'pa-titan-tenable',
      targetAccountId: 'pa-titan-snowflake',
      sourceCredentialId: 'cred-titan-tenable',
      targetCredentialId: 'cred-titan-snowflake',
      name: 'Titan Tenable → Snowflake (v1 legacy)',
      status: IntegrationStatus.Paused,
      createdAt: '2023-01-20T00:00:00Z',
      lastRunAt: '2025-09-01T00:00:00Z',
    },
    // Vertex Labs
    {
      id: 'int-vertex-qualys-snow-1',
      orgId: 'org-vertex',
      integrationTypeId: 'it-qualys-snowflake-v2',
      sourceAccountId: 'pa-vertex-qualys',
      targetAccountId: 'pa-vertex-snowflake',
      sourceCredentialId: 'cred-vertex-qualys',
      name: 'Vertex Qualys → Snowflake',
      status: IntegrationStatus.Paused,
      createdAt: '2024-07-01T00:00:00Z',
    },
  ],

  // ── Provisionings ────────────────────────────────────────────────────────
  provisionings: [
    {
      id: 'prov-acme-dd-dashboard',
      providerAccountId: 'pa-acme-datadog',
      name: 'Acme Security Overview Dashboard',
      status: ProvisioningStatus.Succeeded,
      resourceType: 'dashboard',
      resourceId: 'abc-123-security-overview',
      createdAt: '2022-10-01T00:00:00Z',
      completedAt: '2022-10-01T00:05:00Z',
    },
    {
      id: 'prov-acme-dd-monitor',
      providerAccountId: 'pa-acme-datadog',
      name: 'Acme Credential Expiry Monitor',
      status: ProvisioningStatus.Succeeded,
      resourceType: 'monitor',
      resourceId: 'monitor-cred-expiry-001',
      createdAt: '2023-01-15T00:00:00Z',
      completedAt: '2023-01-15T00:02:00Z',
    },
    {
      id: 'prov-titan-snow-schema',
      providerAccountId: 'pa-titan-snowflake',
      name: 'Titan Snowflake Schema Setup',
      status: ProvisioningStatus.Succeeded,
      resourceType: 'schema',
      resourceId: 'SECURITY.INGEST',
      createdAt: '2023-02-01T00:00:00Z',
      completedAt: '2023-02-01T00:01:00Z',
    },
    {
      id: 'prov-vertex-snow-schema',
      providerAccountId: 'pa-vertex-snowflake',
      name: 'Vertex Snowflake Schema Setup',
      status: ProvisioningStatus.Pending,
      resourceType: 'schema',
      createdAt: '2024-07-05T00:00:00Z',
    },
  ],

  // ── Health Checks ────────────────────────────────────────────────────────
  healthChecks: [
    {
      id: 'hc-cred-not-expired',
      name: 'Credential Not Expired',
      description: 'Fails if the credential has passed its expiry date',
      targetEntityType: TargetEntityType.Credential,
      severity: Severity.Critical,
      defaultParams: { warningDaysBeforeExpiry: 30 },
    },
    {
      id: 'hc-account-reachable',
      name: 'Account Reachable',
      description: 'Verifies the provider account API endpoint is reachable',
      targetEntityType: TargetEntityType.ProviderAccount,
      severity: Severity.High,
    },
    {
      id: 'hc-integration-last-run',
      name: 'Integration Last Run Recency',
      description: 'Fails if integration has not run within the expected window',
      targetEntityType: TargetEntityType.Integration,
      severity: Severity.High,
      defaultParams: { maxStaleHours: 25 },
    },
    {
      id: 'hc-qualys-scan-age',
      name: 'Qualys Scan Age',
      description: 'Fails if the most recent Qualys scan is older than expected',
      targetEntityType: TargetEntityType.ProviderAccount,
      providerId: 'qualys',
      severity: Severity.Medium,
      defaultParams: { maxScanAgeDays: 7 },
    },
  ],

  // ── Health Check Bindings ────────────────────────────────────────────────
  healthCheckBindings: [
    // cred-not-expired bindings
    {
      id: 'hcb-cred-acme-qualys',
      healthCheckId: 'hc-cred-not-expired',
      targetEntityId: 'cred-acme-qualys',
      targetEntityType: TargetEntityType.Credential,
      enabled: true,
    },
    {
      id: 'hcb-cred-acme-splunk',
      healthCheckId: 'hc-cred-not-expired',
      targetEntityId: 'cred-acme-splunk',
      targetEntityType: TargetEntityType.Credential,
      enabled: true,
    },
    {
      id: 'hcb-cred-titan-aws',
      healthCheckId: 'hc-cred-not-expired',
      targetEntityId: 'cred-titan-aws-role',
      targetEntityType: TargetEntityType.Credential,
      enabled: true,
    },
    // account-reachable bindings
    {
      id: 'hcb-acct-acme-qualys',
      healthCheckId: 'hc-account-reachable',
      targetEntityId: 'pa-acme-qualys',
      targetEntityType: TargetEntityType.ProviderAccount,
      enabled: true,
    },
    {
      id: 'hcb-acct-acme-datadog',
      healthCheckId: 'hc-account-reachable',
      targetEntityId: 'pa-acme-datadog',
      targetEntityType: TargetEntityType.ProviderAccount,
      enabled: true,
    },
    {
      id: 'hcb-acct-titan-tenable',
      healthCheckId: 'hc-account-reachable',
      targetEntityId: 'pa-titan-tenable',
      targetEntityType: TargetEntityType.ProviderAccount,
      enabled: true,
    },
    // integration-last-run bindings
    {
      id: 'hcb-int-acme-qualys-snow',
      healthCheckId: 'hc-integration-last-run',
      targetEntityId: 'int-acme-qualys-snow-1',
      targetEntityType: TargetEntityType.Integration,
      enabled: true,
    },
    {
      id: 'hcb-int-titan-tenable-snow',
      healthCheckId: 'hc-integration-last-run',
      targetEntityId: 'int-titan-tenable-snow-1',
      targetEntityType: TargetEntityType.Integration,
      enabled: true,
    },
    // qualys-scan-age bindings
    {
      id: 'hcb-qualys-age-acme',
      healthCheckId: 'hc-qualys-scan-age',
      targetEntityId: 'pa-acme-qualys',
      targetEntityType: TargetEntityType.ProviderAccount,
      params: { maxScanAgeDays: 5 },
      enabled: true,
    },
  ],

  // ── Health Check Runs ────────────────────────────────────────────────────
  healthCheckRuns: [
    // hcb-cred-acme-qualys — expiring credential, should warn
    {
      id: 'hcr-001',
      bindingId: 'hcb-cred-acme-qualys',
      status: RunStatus.Failed,
      ranAt: '2026-04-07T06:00:00Z',
      durationMs: 120,
      message: 'Credential expires in 13 days',
    },
    {
      id: 'hcr-002',
      bindingId: 'hcb-cred-acme-qualys',
      status: RunStatus.Failed,
      ranAt: '2026-04-06T06:00:00Z',
      durationMs: 115,
      message: 'Credential expires in 14 days',
    },
    {
      id: 'hcr-003',
      bindingId: 'hcb-cred-acme-qualys',
      status: RunStatus.Passed,
      ranAt: '2026-04-05T06:00:00Z',
      durationMs: 110,
      message: 'Credential valid',
    },
    // hcb-cred-acme-splunk — expired
    {
      id: 'hcr-004',
      bindingId: 'hcb-cred-acme-splunk',
      status: RunStatus.Failed,
      ranAt: '2026-04-07T06:01:00Z',
      durationMs: 95,
      message: 'Credential expired on 2025-12-01',
    },
    // hcb-acct-acme-qualys — passing
    {
      id: 'hcr-005',
      bindingId: 'hcb-acct-acme-qualys',
      status: RunStatus.Passed,
      ranAt: '2026-04-07T06:05:00Z',
      durationMs: 340,
      message: 'API endpoint responding normally',
    },
    {
      id: 'hcr-006',
      bindingId: 'hcb-acct-acme-qualys',
      status: RunStatus.Passed,
      ranAt: '2026-04-06T06:05:00Z',
      durationMs: 298,
      message: 'API endpoint responding normally',
    },
    // hcb-int-acme-qualys-snow — passing
    {
      id: 'hcr-007',
      bindingId: 'hcb-int-acme-qualys-snow',
      status: RunStatus.Passed,
      ranAt: '2026-04-07T06:10:00Z',
      durationMs: 55,
      message: 'Last run was 4h ago (threshold: 25h)',
    },
    // hcb-int-titan-tenable-snow — passing
    {
      id: 'hcr-008',
      bindingId: 'hcb-int-titan-tenable-snow',
      status: RunStatus.Passed,
      ranAt: '2026-04-07T06:12:00Z',
      durationMs: 52,
      message: 'Last run was 5h ago (threshold: 25h)',
    },
    // hcb-qualys-age-acme
    {
      id: 'hcr-009',
      bindingId: 'hcb-qualys-age-acme',
      status: RunStatus.Passed,
      ranAt: '2026-04-07T06:15:00Z',
      durationMs: 420,
      message: 'Most recent scan was 2 days ago',
    },
  ],

  // ── Scheduled Tasks ──────────────────────────────────────────────────────
  scheduledTasks: [
    // Acme integrations
    {
      id: 'st-acme-qualys-snow',
      orgId: 'org-acme',
      type: TaskType.IntegrationRun,
      targetId: 'int-acme-qualys-snow-1',
      schedule: '0 2 * * *',
      status: TaskStatus.Active,
      lastRunAt: '2026-04-06T02:00:00Z',
      nextRunAt: '2026-04-07T02:00:00Z',
    },
    {
      id: 'st-acme-dd-snow',
      orgId: 'org-acme',
      type: TaskType.IntegrationRun,
      targetId: 'int-acme-dd-snow-1',
      schedule: '0 3 * * *',
      status: TaskStatus.Active,
      lastRunAt: '2026-04-06T03:00:00Z',
      nextRunAt: '2026-04-07T03:00:00Z',
    },
    // Acme health checks
    {
      id: 'st-acme-hc-creds',
      orgId: 'org-acme',
      type: TaskType.HealthCheck,
      targetId: 'hcb-cred-acme-qualys',
      schedule: '0 6 * * *',
      status: TaskStatus.Active,
      lastRunAt: '2026-04-07T06:00:00Z',
      nextRunAt: '2026-04-08T06:00:00Z',
    },
    // Titan integrations
    {
      id: 'st-titan-tenable-snow',
      orgId: 'org-titan',
      type: TaskType.IntegrationRun,
      targetId: 'int-titan-tenable-snow-1',
      schedule: '0 1 * * *',
      status: TaskStatus.Active,
      lastRunAt: '2026-04-06T01:00:00Z',
      nextRunAt: '2026-04-07T01:00:00Z',
    },
    // Titan health checks
    {
      id: 'st-titan-hc-cred',
      orgId: 'org-titan',
      type: TaskType.HealthCheck,
      targetId: 'hcb-cred-titan-aws',
      schedule: '0 6 * * *',
      status: TaskStatus.Active,
      lastRunAt: '2026-04-07T06:00:00Z',
      nextRunAt: '2026-04-08T06:00:00Z',
    },
    // Vertex provisioning
    {
      id: 'st-vertex-prov-snow',
      orgId: 'org-vertex',
      type: TaskType.Provisioning,
      targetId: 'prov-vertex-snow-schema',
      schedule: '0 0 * * 1',
      status: TaskStatus.Paused,
    },
  ],
};
